### ISSUE TITLE
Atom support?

### ISSUE THREAD

**Issue by zypA13510** [ui5experts/ui5-schemas#12]
How do I use this in [Atom](https://atom.io/)?
I managed to install it via npm, but I think maybe I need a way to configure the SDK version?

**Comment by cschuff** [comment]
Hi,

it appears that Atom has [no native support for XML schema validation](https://discuss.atom.io/t/validate-xml-against-xsd/7362/6).

Anyways you could try one of the Atom packages ([linter-autocomplete-jing](https://github.com/aerhard/linter-autocomplete-jing), [linter-xmllint](https://atom.io/packages/linter-xmllint)) mentioned in the above post to make this work.

It would be great if you can report back if you had any success with those. It would be of great help to include a small tutorial in the docs. You are more than welcome to share :)

Since I'm not planning Atom support (since it is obviously not that easy) I'm closing the issue.

BR
Chris

**Comment by zypA13510** [comment]
Hi Chris,

Thanks for your information. I found this package called [autocomplete-xml](https://atom.io/packages/autocomplete-xml) and I'm trying to configure it. So far I figured out the URL `https://openui5.hana.ondemand.com/downloads/schemas/<package-name>.xsd` from your code, but I don't know how to get a version-specific one. Could you please help?

Thanks,
Yuping

**Comment by cschuff** [comment]
Path is https://[SDK].hana.ondemand.com/[VERSION]/downloads/schemas/[LIB].xsd
e.g. https://openui5.hana.ondemand.com/1.44.26/downloads/schemas/sap.m.xsd

But you can actually consume the files downloaded with ui5-schemas directly from %APPDATA%/UI5Experts/ui5-schemas/[SDK]/[VERSION]/[LIB].xsd

Should be something like this:
Win: C:\Users\[User]\AppData\Roaming\UI5Experts\ui5-schemas\openui5\1.44.26\sap.m.xsd
Mac: /Volumes/Data/Users/[USER]/Library/Application Support/UI5Experts/ui5-schemas/openui5/1.44.26/sap.m.xsd
