### ISSUE TITLE
Aggregations that can be written as properties

### ISSUE THREAD

**Issue by miskohut** [ui5experts/ui5-schemas#29]
In sapui5 aggregations can be written as attributes. UI5-schemas does not support this.

![image](https://user-images.githubusercontent.com/10484443/60503014-25e59400-9cbf-11e9-8aa9-8e1a4c64a8ca.png)

When you check the documentation https://sapui5.hana.ondemand.com/#/api/sap.m.ComboBox you notice that _items_ is an aggregation not property. But you can define _items_ as property.

**Comment by cschuff** [comment]
That is a known limitation of the schemas provided by SAPUI5. I'm planning to fix this since the first version of this module but I do not have time... So, for now I will close this issue and add it to the list of 'Known Limitations'.

May be I will look into it someday. Contributions are - of course - always welcome!
