### ISSUE TITLE
Binding Syntax

### ISSUE THREAD

**Issue by JarkkoPeltonen** [ui5experts/ui5-schemas#3]
All attributes with expression binding and input validation get "Wrong attribute value":
![image](https://user-images.githubusercontent.com/19328835/29505447-00ad76ea-864f-11e7-9bde-9b132d927629.png)

Can expression binding be valid input for all attributes?

**Comment by cschuff** [comment]
Hi,

this is a known limitation of the xml schemas provided by SAP. So this could be a feature request for OpenUI5 itself. 

Anyways, I was already looking into these kinds of issues and have some ideas for future versions.

Btw: You are not using [Expression Binding](https://sapui5.hana.ondemand.com/#docs/guide/daf6852a04b44d118963968a1239d2c0.html) in your example. I changed title due to that respect.

BR
Chris

**Comment by JarkkoPeltonen** [comment]
Hello,

Can you share your ideas?

I'm thinking of creating custom type that validates the binding. Then assign this type and current type of attribute as union to all attributes.

Br,
Jarkko

**Comment by cschuff** [comment]
That's exactly what I thought of :) The custom type could use a regex to validate the binding syntax (which could get quite complex: Think of Complex Binding and Expression Binding). The simplest implementation would just additionally allow xsd:string everywhere.

You are most welcome to contribute on this.

**Comment by cschuff** [comment]
Closing this for now since it is mentioned in known limitations and I won't have time to fix this anytime soon.
